package com.zhaohang;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class ConsumerNacos808001Application {

	public static void main(String[] args) {
		SpringApplication.run(ConsumerNacos808001Application.class, args);
	}

}
