server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/depart?useUnicode=true&characterEncoding=utf-8&use
    username: root
    password: root
#    项目名称
  application:
    name: depart-provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos??????
        #        server-addr: 127.0.0.1:8849,127.0.0.1:8851,127.0.0.1:8853
        username: nacos
        password: nacos
